orgsRepos:
  "gitpod-io/gitpod-test-repo":
    - key: "type"
      values:
        - "bug"
        - "deprecate/remove feature"
        - "feature request"
        - "improvement"
        - "incident"
        - "work item"
    - key: "component"
      values:
        - "agent-smith"
        - "blobserve"
        - "browser-extension"
        - "content-service"
        - "dashboard"
        - "db"
        - "gp cli"
        - "gpctl"
        - "ide"
        - "image-builder"
        - "install"
        - "local app"
        - "messagebus"
        - "proxy"
        - "registry-facade"
        - "server"
        - "supervisor"
        - "ws-daemon"
        - "ws-manager-bridge"
        - "ws-manager"
        - "ws-proxy"
        - "ws-scheduler"